### ISSUE TITLE
Using the Trained Model 

### ISSUE THREAD

**Issue by equester** [danielgo13/spacyndo#1]
Hi, 
Thanks for the wonderful work that you have done! 
Would you mind helping me out, with basic steps of uisng your trained model to get NER and Dependecy Parser for Bahasa Language?

Thanks
Lavi Nigam

**Comment by danieldanuega** [comment]
Hi @equester thx for your question and sorry for late reply. 

Currently my model is ready for dependency parser but the NER still need to be updated.
I've updated README file with some informations.

For how to use it I've uploaded a jupyter notebook example in the repo. 
Please see the parser-ner-id-spacy.ipynb file.

Thank you.

**Comment by equester** [comment]
Hi Danielgo, 

Thanks for the update. Make sense now! I am trying to train the model myself. Have some questions: 

-- While spacy-train for POS & Dependecy, i am passing fasttext vector, but somehow it seems to be not working while loading. Any idea's how we can extend the dependecy training with fasttext ID vectors?
- What version of UD are you using? I am trying to use 2.4. 
- Can i colloborate on this? I have been actively working on ID mdoels for NER, POS and Depedency. We can put somehting together. 
- I also would like to do something for Sentiment in ID Lang.

**Comment by danieldanuega** [comment]
Hi @equester,

So sorry for the late reply, I was busy for my graduation. 

Ok for the vector problem, I think you should check Spacy's word vector format.
Try checking spacy repo and dive into their code for how they create the vector model. 
And I think they use genism to build their word vector based on their website.


- What version of UD are you using? I am trying to use 2.4.
**I think it is 2.2**
- Can i colloborate on this? I have been actively working on ID mdoels for NER, POS and Depedency. We can put somehting together.
**Sure, but honestly I'm new on the open source "things". So how do we colaborate?**
- I also would like to do something for Sentiment in ID Lang.
**Yes, I think Spacy also can do Sentiment analysis. Check this link prodi.gy**
